name: RestApi Test

on: [push, pull_request]


jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Go Deps
        run: |
          go mod tidy
      
      - name: Running Tests
        run: |
          go test

      - name: Running Test in aboutapi
        run: |
          cd api/aboutapi
          go test

      - name: Running Test in album
        run: |
          cd api/album
          go test

      - name: Running Test in artist
        run: |
          cd api/artist
          go test

      - name: Running Test in profile
        run: |
          cd api/profile
          go test
      
      - name: Running Test in home
        run: |
          cd api/home
          go test

  macosbuild:
    runs-on: macos-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go Deps
        run: |
          go mod tidy
      
      - name: Running Tests
        run: |
          go test

      - name: Running Test in aboutapi
        run: |
          cd api/aboutapi
          go test

      - name: Running Test in album
        run: |
          cd api/album
          go test

      - name: Running Test in artist
        run: |
          cd api/artist
          go test

      - name: Running Test in profile
        run: |
          cd api/profile
          go test
      
      - name: Running Test in home
        run: |
          cd api/home
          go test