name: Build Restapi In Linux

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      
      - name: Check Golang Version
        run: |
          go version
