name: Build Restapi In Linux

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      
      - name: Check Golang Version
        run: |
          go version
        
        
      - name: Golang Deps Installing
        run: |
          go mod tidy
      
      # - name: Test Restapi

      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.8"
      #     architecture: "x64"

        # run: |
        #   python3 tests/testrestapi.py