name: Test Restapi Linux

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Go Deps
        run: |
          go mod tidy
      
      - name: Running Tests
        run: |
          go test

      - name: Running Test in aboutapi
        run: |
          cd api/aboutapi
          go test

      - name: Running Test in album
        run: |
          cd album/
          go run test