name: Test Restapi macOS

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Go Deps
        run: |
          go mod tidy
      
      - name: Running Tests
        run: |
          go test